version: '3.8'

services:
  # Mail server for development
  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # Web UI
    networks:
      - emllm-network

  # Bot that sends test emails
  bot-generator:
    build:
      context: ../services/bot-generator
    container_name: bot-generator
    env_file: ../.env
    depends_on:
      - mailhog
    networks:
      - emllm-network
    restart: unless-stopped

  # Main processing service
  camel-server:
    build:
      context: ../services/camel-server
    container_name: camel-server
    env_file: ../.env
    depends_on:
      - mailhog
      - ollama
    volumes:
      - ../config:/app/config
    networks:
      - emllm-network
    restart: unless-stopped

  # Client that receives and deploys apps
  client-agent:
    build:
      context: ../services/client-agent
    container_name: client-agent
    env_file: ../.env
    depends_on:
      - mailhog
    volumes:
      - ../deployment:/app/deployment
    networks:
      - emllm-network
    restart: unless-stopped

  # LLM service (optional)
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - emllm-network

  # Web interface
  web-client:
    build:
      context: ../web-client
    container_name: web-client
    ports:
      - "3000:3000"
    env_file: ../.env
    depends_on:
      - mailhog
    networks:
      - emllm-network
    restart: unless-stopped

networks:
  emllm-network:
    driver: bridge

volumes:
  ollama_data:
